### ISSUE TITLE
Code example in index.js

### ISSUE THREAD

**Issue by victorfern91** [malcolmvr/diff-arrays-of-objects#1]
Why are you initializing the function with the random values in the `index.js`?

https://github.com/malcolmvr/diff-arrays-of-objects/blob/883dfc3fb13e866f27c54969778ee06662be4e70/lib/index.js#L90

**Comment by victorfern91** [comment]
Could I send you a merge request to fix that?

**Comment by malcolmvr** [comment]
Yes, go ahead. It appears to be leftover testing code.
